[package]
name = "mettail-examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rhocalc"
path = "rhocalc.rs"

[[bin]]
name = "test_var_identity"
path = "test_var_identity.rs"

[dependencies]
mettail-macros = { path = "../mettail-macros" }
mettail-runtime = { path = "../mettail-runtime" }
moniker = { workspace = true }
lalrpop-util = { workspace = true, features = ["lexer"] }
ascent = { workspace = true }


[build-dependencies]
lalrpop = { workspace = true }